%%  bar

conf = jjtom.config.load();

do_save = true;

norms = [true, false];
monks = [true, false];
targets = { 'face-lr' };

events_subdir = 'recoded_events';
base_prefix = '';
base_subdir = 'new_norm_5s_face_shoulder_move';

c = combvec( 1:numel(norms), 1:numel(monks), 1:numel(targets) );

for i = 1:size(c, 2)
  do_norm = norms(c(1, i));
  per_monk = monks(c(2, i));
  target = targets{c(3, i)};
  
  jjtom_bar_durations2( ...
      'per_monkey',   per_monk ...
    , 'do_normalize', do_norm ...
    , 'normalize_per_roi', false ...
    , 'apple_or_hand', 'hand' ...
    , 'target_roi',   target ...
    , 'do_save',      do_save ...
    , 'config',       conf ...
    , 'files',    {'Cn', 'Kr'} ...
    , 'separate_apparatus_and_face', true ...
    , 'event_subdir', events_subdir ...
    , 'base_prefix', base_prefix ...
    , 'base_subdir', base_subdir ...
    , 'recoded_normalization_event_name', 'occluder down' ...
    , 'recoded_normalization_look_ahead', 3e3 ...
    , 'start_event_name', 'shoulder move' ...
    , 'look_back', 0 ...
    , 'look_ahead', 6e3 ...
  );
end

%%  timecourse

do_save = true;

norms = [ true, false ];
targets = { 'box-lr', 'apparatus-lr', 'face-lr' };

c = combvec( 1:numel(norms), 1:numel(targets) );

for i = 1:size(c, 2)
  do_norm = norms(c(1, i));
  target = targets{c(2, i)};
  
  jjtom_timecourse_2( ...
      'do_normalize',   do_norm ...
    , 'target_roi',     target ...
    , 'do_save',        do_save ...
    , 'config',         conf ...
    , 'not_files',      {'Cn', 'Kr'} ...
  );
end